[package]
name = "ux-framework"
version = "0.1.1"
authors = ["Victor Dudochkin <dudochkin.victor@gmail.com>"]
readme = "README.md"
homepage = "https://angular-rust.github.io/ux-framework"
repository = "https://github.com/angular-rust/ux-framework"
documentation = "https://docs.rs/ux-framework"
description = "Backend agnostic GUI framework"
keywords = ["wasm", "web", "material-design", "material-components", "gtk"]
categories = ["wasm", "web-programming", "gui"]
edition = "2018"
license = "MPL-2.0"

[badges]
maintenance = { status = "actively-developed" }

[lib]
name = "ux"

[package.metadata.docs.rs]
features = ["dox"]

[features]
dox = ["ux-animate/dox", "ux-charts/dox", "ux-dx/dox", "ux-components/dox"]
# , "x11/dox"
# "gobject-sys/dox", "pango/dox"

[dependencies]
# log = "0.4"
# bitflags = "1.0"
ruex = "0.1.1"
ux-macro = "0.1.0"
ux-primitives = "0.1.4"
ux-dx = "0.1.1"
ux-dataflow = "0.1.2"
ux-animate = "0.1.5"
ux-charts = "0.1.3"
# ux-barcode = "0.1"
ux-components = "0.1.2"
# simplecss = "0.2.0"

# [target.'cfg(not(target_arch = "wasm32"))'.dependencies]
# # gobject-sys = "0.10"
# # glib = "0.10"
# # pango = "0.9"
# # x11 = "2.18"

# # starup notifications
# notify-rust = "4"

# [target.'cfg(target_arch = "wasm32")'.dependencies]
# wasm-bindgen = "0.2"
# js-sys = "0.3"
# wasm-bindgen-futures = "0.4"
# wasm-logger = "0.2"
# gloo = "0.2"
# wasm-bindgen-test = "0.3"

# [target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
# version = "0.3"
# features = [
#   'KeyboardEvent',
#   "ValidityState",
#   "CustomEvent",
#   "Node",
#   "Element",
#   "HtmlElement",
#   "Window",
#   "Document",
#   "CanvasRenderingContext2d",
#   "TextMetrics",
#   "HtmlCanvasElement",
#   "HtmlImageElement",
#   "SvgImageElement",
#   "HtmlVideoElement",
#   "ImageBitmap",
#   "CanvasWindingRule",
#   "Path2d",
#   "CanvasPattern",
#   "CanvasGradient",
#   "HitRegionOptions",
#   "ImageData",
#   "DomMatrix"
# ]

# [dev-dependencies]
