[package]
name = "ux-framework"
version = "0.1.0"
authors = ["Victor Dudochkin <dudochkin.victor@gmail.com>"]
edition = "2018"

[lib]
name = "ux"

[dependencies]
ux-primitives = "0.1"
ux-animate = "0.1"
ux-barcode = "0.1"
ux-charts = "0.1"
ux-components = "0.1"